###

GET http://localhost:3000/logs

###
POST http://localhost:3000/logs
Content-Type: application/json

{   
    "message": ["test post-save"],
    "type": "server",
    "level": "info"
}

###

GET http://localhost:3000/logs/62c5abede75cf83d3526d77f
