###

GET http://localhost:3000/logs

###
POST http://localhost:3000/logs
Content-Type: application/json

{   
    "message": ["test post-save"],
    "type": "server",
    "level": "info"
}

###

GET http://localhost:3000/logs/62c5abede75cf83d3526d77f

###

POST http://localhost:3000/friendship/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZmlyc3ROYW1lIjoiWWFjaW5lIiwiaWF0IjoxNjU4OTYwMTE2LCJleHAiOjE2OTA1MTc3MTZ9.6s1ah9xhyBuSvnsxTHVHs0xjpFKfDvgDaro4zzjxg9Y

{
    "id_receiver": 10
}

###
GET  http://localhost:3000/friendship/show
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImZpcnN0TmFtZSI6InRlc3QiLCJpYXQiOjE2NTg5NjE2MjUsImV4cCI6MTY5MDUxOTIyNX0.DjQUXzQ1oRyk7LLKssu9VSWUUlFl2CmTtkA9Fl2mjck

###

GET  http://localhost:3000/friendship/pendings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImZpcnN0TmFtZSI6InRlc3QiLCJpYXQiOjE2NTg5NjE3NjEsImV4cCI6MTY5MDUxOTM2MX0.IRO2iPDeW60uFpfveUsuhGHieYuewtFoQiGtxM3jvy4

###
POST http://localhost:3000/friendship/request-answer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImZpcnN0TmFtZSI6InRlc3QiLCJpYXQiOjE2NTg5NjE3NjEsImV4cCI6MTY5MDUxOTM2MX0.IRO2iPDeW60uFpfveUsuhGHieYuewtFoQiGtxM3jvy4
    
{
        "id_sender": 2,
        "answer": "accept"
}

###
PUT http://localhost:3000/messages/284
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZmlyc3ROYW1lIjoiVGhlIHJlcXVlc3QgaGFzIHN1Y2NlZWRlZC4iLCJpYXQiOjE2NTcwMzA5ODUsImV4cCI6MTY4ODU4ODU4NX0.S3IFe_e0_RBuOk25uZfYEPxWi911s2tVEAoPltGVrpQ

{
    "state": "update"
}
###

POST http://localhost:3000/messages
Content-Type: application/json

{   
    "content": "Ça va Moncef ?",
    "authorId": 4,
    "conversationId": 30
}

###

DELETE http://localhost:3000/messages/1


###

GET http://localhost:3000/conversations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZmlyc3ROYW1lIjoiVGhlIHJlcXVlc3QgaGFzIHN1Y2NlZWRlZC4iLCJpYXQiOjE2NTcwMjY5NDksImV4cCI6MTY4ODU4NDU0OX0.Z-f6jbd_wQu6Ae-lDQCqZoYh9cHqZ92f9W7rYjV_2l0

###

GET http://localhost:3000/conversations/85
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZmlyc3ROYW1lIjoiVGhlIHJlcXVlc3QgaGFzIHN1Y2NlZWRlZC4iLCJpYXQiOjE2NTcwMjY5NDksImV4cCI6MTY4ODU4NDU0OX0.Z-f6jbd_wQu6Ae-lDQCqZoYh9cHqZ92f9W7rYjV_2l0

###

GET http://localhost:3000/myconversations/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZmlyc3ROYW1lIjoiVGhlIHJlcXVlc3QgaGFzIHN1Y2NlZWRlZC4iLCJpYXQiOjE2NTcwMjY5NDksImV4cCI6MTY4ODU4NDU0OX0.Z-f6jbd_wQu6Ae-lDQCqZoYh9cHqZ92f9W7rYjV_2l0

###

POST http://localhost:3000/conversations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZmlyc3ROYW1lIjoiVGhlIHJlcXVlc3QgaGFzIHN1Y2NlZWRlZC4iLCJpYXQiOjE2NTcwMjY5NDksImV4cCI6MTY4ODU4NDU0OX0.Z-f6jbd_wQu6Ae-lDQCqZoYh9cHqZ92f9W7rYjV_2l0

{
    "firstUserId": 4,
    "secondUserId": 7
}

###
PUT http://localhost:3000/conversations/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZmlyc3ROYW1lIjoiVGhlIHJlcXVlc3QgaGFzIHN1Y2NlZWRlZC4iLCJpYXQiOjE2NTcwMzA5ODUsImV4cCI6MTY4ODU4ODU4NX0.S3IFe_e0_RBuOk25uZfYEPxWi911s2tVEAoPltGVrpQ

{
    "lastMessageId": 1,
    "firstUserId": 1,
    "secondUserId": 2
}

###

DELETE http://localhost:3000/conversations/68
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZmlyc3ROYW1lIjoiVGhlIHJlcXVlc3QgaGFzIHN1Y2NlZWRlZC4iLCJpYXQiOjE2NTcwMzA5ODUsImV4cCI6MTY4ODU4ODU4NX0.S3IFe_e0_RBuOk25uZfYEPxWi911s2tVEAoPltGVrpQ

###
GET http://localhost:3000/participants
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZmlyc3ROYW1lIjoiVGhlIHJlcXVlc3QgaGFzIHN1Y2NlZWRlZC4iLCJpYXQiOjE2NTcwMjY5NDksImV4cCI6MTY4ODU4NDU0OX0.Z-f6jbd_wQu6Ae-lDQCqZoYh9cHqZ92f9W7rYjV_2l0
###

###
POST http://localhost:3000/participants
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZmlyc3ROYW1lIjoiVGhlIHJlcXVlc3QgaGFzIHN1Y2NlZWRlZC4iLCJpYXQiOjE2NTcwMjY5NDksImV4cCI6MTY4ODU4NDU0OX0.Z-f6jbd_wQu6Ae-lDQCqZoYh9cHqZ92f9W7rYjV_2l0

{
    "userId": 2,
    "conversationId": 10
}


